"""initial_phase1_schema

Revision ID: 7f6eb611e707
Revises: 
Create Date: 2026-09-12 20:03:36.020277

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision = '7f6eb611e707'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # Ensure pgvector extension exists before table creation
    op.execute("CREATE EXTENSION IF NOT EXISTS vector;")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('branches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('address', sa.String(length=300), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('opening_hours_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('branches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_branches_active'), ['active'], unique=False)

    op.create_table('customers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customers_phone'), ['phone'], unique=True)

    op.create_table('knowledge_documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('index_status', sa.String(length=20), nullable=False),
    sa.Column('last_indexed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('index_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("index_status IN ('PENDING', 'INDEXING', 'READY', 'FAILED')", name='ck_knowledge_docs_index_status'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('knowledge_documents', schema=None) as batch_op:
        batch_op.create_index('ix_knowledge_docs_category_active', ['category', 'active'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_documents_active'), ['active'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_documents_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_documents_index_status'), ['index_status'], unique=False)

    op.create_table('packages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('price >= 0', name='ck_packages_price_non_negative'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_packages_active'), ['active'], unique=False)
        batch_op.create_index(batch_op.f('ix_packages_name'), ['name'], unique=True)

    op.create_table('test_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('test_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_test_categories_active'), ['active'], unique=False)
        batch_op.create_index(batch_op.f('ix_test_categories_slug'), ['slug'], unique=True)

    op.create_table('availability_slots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('visit_type', sa.String(length=20), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.Time(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('reserved_count', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.CheckConstraint("(visit_type = 'BRANCH' AND branch_id IS NOT NULL) OR (visit_type = 'HOME' AND branch_id IS NULL)", name='ck_slots_branch_for_branch_visit'),
    sa.CheckConstraint("visit_type IN ('BRANCH', 'HOME')", name='ck_slots_visit_type'),
    sa.CheckConstraint('capacity >= 0', name='ck_slots_capacity_non_negative'),
    sa.CheckConstraint('reserved_count <= capacity', name='ck_slots_reserved_le_capacity'),
    sa.CheckConstraint('reserved_count >= 0', name='ck_slots_reserved_non_negative'),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('availability_slots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_availability_slots_active'), ['active'], unique=False)
        batch_op.create_index(batch_op.f('ix_availability_slots_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index('ix_slots_branch_date_active', ['branch_id', 'date', 'active'], unique=False)
        batch_op.create_index('ix_slots_visit_type_date', ['visit_type', 'date'], unique=False)
        batch_op.create_index('uq_slots_branch_date_time', ['branch_id', 'date', 'time'], unique=True, postgresql_where=sa.text("visit_type = 'BRANCH'"))
        batch_op.create_index('uq_slots_home_date_time', ['date', 'time'], unique=True, postgresql_where=sa.text("visit_type = 'HOME' AND branch_id IS NULL"))

    op.create_table('knowledge_chunks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('search_vector', sa.Text().with_variant(postgresql.TSVECTOR(), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['knowledge_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'chunk_index', name='uq_chunks_doc_chunk_index')
    )
    with op.batch_alter_table('knowledge_chunks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_chunks_document_id'), ['document_id'], unique=False)
        batch_op.create_index('ix_knowledge_chunks_search_vector', ['search_vector'], unique=False, postgresql_using='gin')

    op.create_table('lab_tests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('short_description', sa.Text(), nullable=False),
    sa.Column('sample_type', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('result_turnaround_text', sa.String(length=150), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('price >= 0', name='ck_lab_tests_price_non_negative'),
    sa.ForeignKeyConstraint(['category_id'], ['test_categories.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lab_tests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lab_tests_active'), ['active'], unique=False)
        batch_op.create_index(batch_op.f('ix_lab_tests_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lab_tests_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_lab_tests_name'), ['name'], unique=False)

    op.create_table('bookings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('booking_reference', sa.String(length=50), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('availability_slot_id', sa.Integer(), nullable=False),
    sa.Column('visit_type', sa.String(length=20), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('scheduled_time', sa.Time(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('idempotency_key', sa.String(length=100), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("(visit_type = 'BRANCH' AND branch_id IS NOT NULL) OR (visit_type = 'HOME')", name='ck_bookings_branch_for_branch_visit'),
    sa.CheckConstraint("status IN ('CONFIRMED', 'COMPLETED', 'CANCELLED')", name='ck_bookings_status'),
    sa.CheckConstraint("visit_type IN ('BRANCH', 'HOME')", name='ck_bookings_visit_type'),
    sa.ForeignKeyConstraint(['availability_slot_id'], ['availability_slots.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bookings_booking_reference'), ['booking_reference'], unique=True)
        batch_op.create_index(batch_op.f('ix_bookings_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index('ix_bookings_customer_id', ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_idempotency_key'), ['idempotency_key'], unique=True)
        batch_op.create_index('ix_bookings_scheduled_date', ['scheduled_date'], unique=False)
        batch_op.create_index('ix_bookings_slot_id', ['availability_slot_id'], unique=False)
        batch_op.create_index('ix_bookings_status', ['status'], unique=False)

    op.create_table('conversation_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('selected_test_id', sa.Integer(), nullable=True),
    sa.Column('selected_package_id', sa.Integer(), nullable=True),
    sa.Column('current_state', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('pending_action', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('pending_clarification', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('active_snapshot_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['selected_package_id'], ['packages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['selected_test_id'], ['lab_tests.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversation_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversation_sessions_session_id'), ['session_id'], unique=True)

    op.create_table('package_tests',
    sa.Column('package_id', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_id'], ['lab_tests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('package_id', 'test_id'),
    sa.UniqueConstraint('package_id', 'test_id', name='uq_package_tests_package_test')
    )
    op.create_table('booking_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=True),
    sa.Column('package_id', sa.Integer(), nullable=True),
    sa.Column('unit_price_snapshot', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.CheckConstraint('(test_id IS NOT NULL AND package_id IS NULL) OR (test_id IS NULL AND package_id IS NOT NULL)', name='ck_booking_items_single_item_type'),
    sa.CheckConstraint('unit_price_snapshot >= 0', name='ck_booking_items_price_non_negative'),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['test_id'], ['lab_tests.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('booking_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_booking_items_booking_id'), ['booking_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_items_package_id'), ['package_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_items_test_id'), ['test_id'], unique=False)

    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('intent', sa.String(length=100), nullable=True),
    sa.Column('metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("role IN ('user', 'assistant', 'system')", name='ck_chat_messages_role'),
    sa.ForeignKeyConstraint(['session_id'], ['conversation_sessions.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.create_index('ix_chat_messages_session_created', ['session_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_messages_session_id'), ['session_id'], unique=False)

    op.create_table('home_visits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=300), nullable=False),
    sa.Column('area', sa.String(length=100), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('REQUESTED', 'SCHEDULED', 'DISPATCHED', 'SAMPLE_COLLECTED', 'CANCELLED')", name='ck_home_visits_status'),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('home_visits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_home_visits_booking_id'), ['booking_id'], unique=True)

    op.create_table('search_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('sequence_no', sa.Integer(), nullable=False),
    sa.Column('query', sa.String(length=500), nullable=False),
    sa.Column('criteria', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('items', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['conversation_sessions.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'sequence_no', name='uq_search_snapshots_session_seq')
    )
    with op.batch_alter_table('search_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_search_snapshots_session_id'), ['session_id'], unique=False)

    # Explicitly add circular FK from conversation_sessions to search_snapshots after both tables exist
    op.create_foreign_key(
        'fk_conversation_sessions_active_snapshot_id',
        'conversation_sessions',
        'search_snapshots',
        ['active_snapshot_id'],
        ['id'],
        ondelete='SET NULL',
    )

    # Trigger for automatic KnowledgeChunk.search_vector maintenance on INSERT/UPDATE
    op.execute("""
    CREATE OR REPLACE FUNCTION knowledge_chunks_search_vector_trigger() RETURNS trigger AS $$
    BEGIN
        NEW.search_vector := to_tsvector('simple', coalesce(NEW.content, ''));
        RETURN NEW;
    END
    $$ LANGUAGE plpgsql;

    CREATE TRIGGER trg_knowledge_chunks_search_vector
    BEFORE INSERT OR UPDATE OF content ON knowledge_chunks
    FOR EACH ROW EXECUTE FUNCTION knowledge_chunks_search_vector_trigger();
    """)


def downgrade():
    # Remove search_vector trigger and function
    op.execute("""
    DROP TRIGGER IF EXISTS trg_knowledge_chunks_search_vector ON knowledge_chunks;
    DROP FUNCTION IF EXISTS knowledge_chunks_search_vector_trigger();
    """)

    # Drop circular foreign key constraint before dropping referenced table
    op.drop_constraint(
        'fk_conversation_sessions_active_snapshot_id',
        'conversation_sessions',
        type_='foreignkey',
    )

    with op.batch_alter_table('search_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_search_snapshots_session_id'))

    op.drop_table('search_snapshots')
    with op.batch_alter_table('home_visits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_home_visits_booking_id'))

    op.drop_table('home_visits')
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_messages_session_id'))
        batch_op.drop_index('ix_chat_messages_session_created')

    op.drop_table('chat_messages')
    with op.batch_alter_table('booking_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_booking_items_test_id'))
        batch_op.drop_index(batch_op.f('ix_booking_items_package_id'))
        batch_op.drop_index(batch_op.f('ix_booking_items_booking_id'))

    op.drop_table('booking_items')
    op.drop_table('package_tests')
    with op.batch_alter_table('conversation_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversation_sessions_session_id'))

    op.drop_table('conversation_sessions')
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_index('ix_bookings_status')
        batch_op.drop_index('ix_bookings_slot_id')
        batch_op.drop_index('ix_bookings_scheduled_date')
        batch_op.drop_index(batch_op.f('ix_bookings_idempotency_key'))
        batch_op.drop_index('ix_bookings_customer_id')
        batch_op.drop_index(batch_op.f('ix_bookings_branch_id'))
        batch_op.drop_index(batch_op.f('ix_bookings_booking_reference'))

    op.drop_table('bookings')
    with op.batch_alter_table('lab_tests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lab_tests_name'))
        batch_op.drop_index(batch_op.f('ix_lab_tests_code'))
        batch_op.drop_index(batch_op.f('ix_lab_tests_category_id'))
        batch_op.drop_index(batch_op.f('ix_lab_tests_active'))

    op.drop_table('lab_tests')
    with op.batch_alter_table('knowledge_chunks', schema=None) as batch_op:
        batch_op.drop_index('ix_knowledge_chunks_search_vector', postgresql_using='gin')
        batch_op.drop_index(batch_op.f('ix_knowledge_chunks_document_id'))

    op.drop_table('knowledge_chunks')
    with op.batch_alter_table('availability_slots', schema=None) as batch_op:
        batch_op.drop_index('uq_slots_home_date_time', postgresql_where=sa.text("visit_type = 'HOME' AND branch_id IS NULL"))
        batch_op.drop_index('uq_slots_branch_date_time', postgresql_where=sa.text("visit_type = 'BRANCH'"))
        batch_op.drop_index('ix_slots_visit_type_date')
        batch_op.drop_index('ix_slots_branch_date_active')
        batch_op.drop_index(batch_op.f('ix_availability_slots_branch_id'))
        batch_op.drop_index(batch_op.f('ix_availability_slots_active'))

    op.drop_table('availability_slots')
    with op.batch_alter_table('test_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_test_categories_slug'))
        batch_op.drop_index(batch_op.f('ix_test_categories_active'))

    op.drop_table('test_categories')
    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_packages_name'))
        batch_op.drop_index(batch_op.f('ix_packages_active'))

    op.drop_table('packages')
    with op.batch_alter_table('knowledge_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_documents_index_status'))
        batch_op.drop_index(batch_op.f('ix_knowledge_documents_category'))
        batch_op.drop_index(batch_op.f('ix_knowledge_documents_active'))
        batch_op.drop_index('ix_knowledge_docs_category_active')

    op.drop_table('knowledge_documents')
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customers_phone'))

    op.drop_table('customers')
    with op.batch_alter_table('branches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_branches_active'))

    op.drop_table('branches')
    # ### end Alembic commands ###
